add: publishing code
sunrabbit123/GRIG-OpenAPI pull request #14
Opened 2021-07-27 13:58 UTC by chanwoo00106

폼 태그 명세는 제외하고 퍼블리싱 코드를 작성했어요.

2021-07-27 14:05 UTC, chanwoo00106 commented
> 작성 완료 했어요.

2021-07-27 15:04 UTC, iseolin76 requested changes
그래도 수고하셨습니다! 짧은 시간내에 잘 끝내셨어요 :)

조금 더 힘내주세요!

2021-07-27 15:04 UTC, iseolin76 commented on src/static/style.css
> +    position: absolute;
여기도 absolute

2021-07-27 15:04 UTC, iseolin76 commented on src/static/style.css
> +    position: relative;
여기 `position: relative;` 는 왜 쓰인건가요???

2021-07-27 15:04 UTC, iseolin76 commented on src/static/style.css
> +    position: relative;
여기도

2021-07-28 08:06 UTC, iseolin76 approved these changes
수고하셨습니다! 완전 잘했어요 👍

2021-07-28 08:40 UTC, sunrabbit123 commented
Resolve 된 사항들은 `Resolve conversation` 눌러주세요 !

2021-07-28 08:42 UTC, sunrabbit123 reviewed
LGTM

2021-07-28 08:58 UTC, merged